### ISSUE TITLE
Fields documented for reverse-claims api endpoint are incorrect

### ISSUE THREAD

**Issue by mouse-reeve** [inventaire/inventaire-api#5]
I'm looking at the documentation available here: https://api.inventaire.io/#!/Entities/get_entities_action_reverse_claims

It appears to be generated by: https://github.com/inventaire/inventaire-api/blob/master/inv-spec/paths/entities/reverse-claims.yaml

Parameter | Value | Description | Parameter Type | Data Type
-- | -- | -- | -- | --
property |   | The claim's property URI. | query | string
uri |   | An entity URI. | query | string
refresh | true            false  (default) | Request non-cached data | query | boolean

The documentation lists this path as requiring a `uri` parameter, but if you run it as provided, it returns the following error:
```
{
  "status": 400,
  "status_verbose": "missing parameter in query: value",
  "error_type": "missing_parameter",
  "error_name": "missing_value",
  "context": {
    "query": {
      "action": "reverse-claims",
      "property": "wdt:P50",
      "uri": "wd:Q2196",
      "refresh": "false"
    }
  },
  "warnings": {
    "parameters": [
      "unexpected parameter: uri"
    ]
  }
}
```

The correct path appears to take `value` instead of `uri`, and the resulting url works correctly if fixed accordingly.

**Comment by maxlath** [comment]
Thanks for reporting, the doc wasn't updated after this [breaking change](https://github.com/inventaire/inventaire/commit/f84ac8ffedd9509ce5ea74c34c20b20221a941f3). Fixed in 4678172
